name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: composer install

      - name: Set up Apache
        uses: shivammathur/setup-apache@v1

      - name: Configure Apache for PHP
        run: sudo cp .github/workflows/apache-config.conf /etc/apache2/sites-available/000-default.conf

      - name: Enable Apache rewrite module
        run: sudo a2enmod rewrite

      - name: Restart Apache
        run: sudo service apache2 restart
